homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data
  elevation: 60
  # C for Celsius, F for Fahrenheit
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_pass

device_tracker:
  platform: owntracks
  max_gps_accuracy: 200

zone:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  radius: 100
  icon: mdi:home-map-marker

zone 2:
  name: !secret ware_name
  latitude: !secret ware_lat
  longitude: !secret ware_long
  radius: 150
  icon: mdi:city

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

#Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
#sun:

netatmo:
  api_key: !secret netatmo_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_user
  password: !secret netatmo_pass

# Weather Prediction
sensor:
  platform: yr

logger: 
  default: info
  logs:
    homeassistant.components.camera: critical

sensor 2:
  platform: worldclock
  time_zone: America/Los_Angeles
  name: Portland

camera:
  platform: uvc
  nvr: localhost
  key: !secret uvc_key

sensor 3:
  platform: netatmo
  station: !secret netatmo_station
  modules:
    Living_Room:
      - temperature
      - humidity
      - noise
      - pressure
      - co2
      - wifi_status
    Bedroom:
      - temperature
      - battery_vp
      - min_temp
      - max_temp
      - humidity

sensor 4:
   platform: plex
   name: !secret plex_name
   host: !secret plex_host
   port: 32400
   username: !secret plex_user
   password: !secret plex_pass
   server: !secret plex_name

sensor 5:
  platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload

sensor 6:
  platform: forecast
  api_key: !secret forecast_api
  monitored_conditions:
    - summary
#    - minutely_summary
#    - hourly_summary
#    - daily_summary
#    - icon
    - nearest_storm_distance
#    - nearest_storm_bearing
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
sensor 7:
  platform: nzbget
  base_url: !secret nzbget_url
  username: !secret nzbget_user
  password: !secret nzbget_pass
  monitored_variables:
    - ArticleCacheMB
    - DownloadRate
    - DownloadPaused
    - FreeDiskSpaceMB
    - PostPaused
    - RemainingSizeMB

panel_iframe:
  router:
    title: 'Router'
    icon: 'mdi:router-wireless'
    url: 'http://172.16.23.1'
  sonarr:
    title: 'Sonarr'
    icon: 'mdi:television'
    url: 'http://172.16.23.121:8989'

#################################################################
## Includes
#################################################################

group: !include groups.yaml

#scene: !include scenes.yaml

#automation: !include automation.yaml

#input_boolean: !include input_boolean.yaml
